CREATE TABLE IF NOT EXISTS player_stats_pitching (
  player_id integer NOT NULL,
  season character(4) NOT NULL,
  
  air_outs integer,
  at_bats integer,
  balks integer,
  base_on_balls integer,
  batters_faced integer,
  blown_saves integer,
  catchers_interference integer,
  caught_stealing integer,
  complete_games integer,
  doubles integer,
  earned_runs integer,
  games_finished integer,
  games_pitched integer,
  games_played integer,
  games_started integer,
  ground_into_double_play integer,
  ground_outs integer,
  hit_batsmen integer,
  hit_by_pitch integer,
  hits integer,
  holds integer,
  home_runs integer,
  inherited_runners integer,
  inherited_runners_scored integer,
  innings_pitched varchar(7),
  innings_pitched_complete integer,
  innings_pitched_partial integer,
  intentional_walks integer,
  losses integer,
  number_of_pitches integer,
  outs integer,
  pickoffs integer,
  runs integer,
  sac_bunts integer,
  sac_flies integer,
  save_opportunities integer,
  saves integer,
  shutouts integer,
  stolen_bases integer,
  strike_outs integer,
  strikes integer,
  total_bases integer,
  triples integer,
  wild_pitches integer,
  wins integer,

  created_at timestamp with time zone,
  updated_at timestamp with time zone,

  PRIMARY KEY (player_id, season),
  CONSTRAINT fk_player
    FOREIGN KEY(player_id)
    REFERENCES players(id),
  CONSTRAINT fk_season
    FOREIGN KEY(season)
    REFERENCES seasons(id)
);
